extends:
  - standard
  - plugin:react/recommended
  - plugin:flowtype/recommended
plugins:
  - flowtype
rules:
  react/prop-types: 0
globals:
  describe: true
  expect: true
  it: true
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
