/* eslint-disable import/prefer-default-export */
export const WpActionTypes = {
  LIST_POSTS: 'LIST_POSTS',
  SET_POSTS: 'SET_POSTS',
  UNSET_POSTS: 'UNSET_POSTS',
  LIST_SUB_POSTS: 'LIST_SUB_POSTS',
  SET_SUB_POSTS: 'SET_SUB_POSTS',
  UNSET_SUB_POSTS: 'UNSET_SUB_POSTS',
  CLEAR_SUB_POSTS: 'CLEAR_SUB_POSTS',
  GET_POST: 'GET_POST',
  SET_POST: 'SET_POST',
  UNSET_POST: 'UNSET_POST'
}
